name=input("enter your name")
gender=input("enter your gender")
age=input("enter your age")
college=input("enter your college name")
branch=input("enter your branch")
print("your nmae is",name)
print("your gender is",gender)
print("your age is",age)
print("your college is",college)
print("your branch is",branch)
